name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust to match your default branch

  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages:
    runs-on: ubuntu-lastest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3