name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust to match your default branch

  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .  # Ensure your dependencies are here

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html  # Adjust if using a different makefile or builder
          touch _build/html/.nojekyll  # Ensures proper rendering on GitHub Pages

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build/html  # Adjust if your output directory is different

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2